# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.
# It is just for read timelime registers from this app not has any other privilege
twitter: &twitter
  consumer_key: 'EvOOnRd2P7nlZMib3vD5etiKv'
  consumer_secret: 'HVOoGvF2aUxnb2kk3fFNnnt1jDCvQHPWpEtxAUl7dhBXggWCiN'
  oauth_token: '131400477-3vO1pJfDkSvYcZbFUKGUUlFbt6K0QERM7EJdwIRd'
  oauth_token_secret: 'bLgCwPK6SSzzqmQ1sPjxULxkQNBGgUpv9T1IR6FnwrmFE'

development:
  secret_key_base: 89090b7e886b5043ffc316ac8fb5c9c340dc7d5e38336f299bce3293cc25c75d77eec93794dddd79b54088b2a12cbfb64acb3dec3f29e8197e125a0e5facbc4b
  <<: *twitter

test:
  secret_key_base: 2c20b5a51d7cd69b587f5caef736f08a1613195b7dcc63737cb3dc2e7fd225fc303fe28bc8f103e27adf18f6f25735518b957cca99c35710f0c8f1e62664169d
  <<: *twitter

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  <<: *twitter